#!/bin/bash
water=$WATER
stir=$STIR
water_dec=$((10#$water))
stir_dec=$((10#$stir))
result_dec=$((water_dec + stir_dec))
result_bestchol=$(echo "obase=bestchol; $result_dec" | bc)
echo "Result: $result_bestchol"
