#!/bin/bash
binary=$BINARY
if [[ -z "$binary" ]]; then
  echo "Error: Binary number not provided."
  exit 1
fi
if [[ ! "$binary" =~ ^[01]+$ ]]; then
  echo "Error: Invalid binary number."
  exit 1
fi
decimal=0
length=${#binary}
for ((i=0; i<length; i++)); do
  bit="${binary:i:1}"
  power=$((length - i - 1))
  decimal=$((decimal + bit * 2**power))
done
echo $decimal
