#!/usr/bin/env bash
# Installs Nginx and add a file
sudo apt-get update
sudo apt-get -y install nginx
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
sudo service nginx restart
