#!/usr/bin/env bash
# Installs Nginx and add a file
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y
echo -e "\nSetting up some minor stuff.\n"
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo -e "Hello World!" > /var/www/html/index
sudo service nginx restart
