#!/usr/bin/env bash
# Installs, configures, and starts the server
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 Moved Permanently;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
