#!/usr/bin/env bash
# Bash script that configures an Nginx server to have custom 404 page with a custom text
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/uche.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
sudo bash -c 'cat <<EOL > /etc/nginx/sites-enabled/default
server {
    listen 80;
    listen [::]:80 default_server;

    root /var/www/html;
    index uche.html index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.github.com/Cofucan;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html/;
        internal;
    }
}
EOL'
sudo service nginx restart
