#!/usr/bin/env bash
# Do so many thing like displaying, creating and deleting
finisher() {
rm /var/run/myscript.pid
exit
}

echo "$$" > /var/run/myscript.pid
while true
do
echo "To infinity and beyond"
sleep 2
trap 'echo "Y U no love me?!" SIGINT
trap 'echo "I hate the kill command" && finisher' SIGTERM
trap 'finisher' SIGQUIT
done
